package music

import (
	"fmt"
	"strconv"
	"strings"
)

// WriteABC renders the score as ABC notation, a widely used, human-readable
// text standard for music (abcnotation.com). Each chess move becomes one bar,
// which keeps the file easy to read and makes accidentals unambiguous.
//
// The output can be opened in any ABC tool (e.g. EasyABC, abcjs, abc2midi) to
// view the staff notation, play it back, or export to other formats.
func (s Score) WriteABC() string {
	var b strings.Builder

	// File header and tune header (information fields).
	b.WriteString("%abc-2.1\n")
	b.WriteString("X:1\n")
	fmt.Fprintf(&b, "T:%s\n", sanitizeField(s.Title))
	b.WriteString("C:Generated by chess-to-music\n")
	b.WriteString("M:none\n")   // free meter: bars group notes without a fixed length
	b.WriteString("L:1/8\n")    // unit note length is an eighth note
	fmt.Fprintf(&b, "Q:1/4=%d\n", s.Tempo)
	b.WriteString("K:C\n")

	const barsPerLine = 4
	count := 0
	for _, n := range s.Notes {
		b.WriteString(abcNote(n))
		b.WriteString(" | ")
		count++
		if count%barsPerLine == 0 {
			b.WriteString("\n")
		}
	}
	if count%barsPerLine != 0 {
		b.WriteString("\n")
	}
	return b.String()
}

// abcNote renders one Note (single pitch or chord) as an ABC token.
func abcNote(n Note) string {
	length := ""
	if n.Duration > 1 {
		length = strconv.Itoa(n.Duration)
	}
	if len(n.Pitches) == 1 {
		return abcPitch(n.Pitches[0]) + length
	}
	var b strings.Builder
	b.WriteByte('[')
	for _, p := range n.Pitches {
		b.WriteString(abcPitch(p))
	}
	b.WriteByte(']')
	b.WriteString(length)
	return b.String()
}

// abcPitchClass maps a pitch class (0..11) to an ABC letter, using sharps.
var abcPitchClass = [12]struct {
	letter   byte
	accident string
}{
	{'C', ""}, {'C', "^"}, {'D', ""}, {'D', "^"},
	{'E', ""}, {'F', ""}, {'F', "^"}, {'G', ""},
	{'G', "^"}, {'A', ""}, {'A', "^"}, {'B', ""},
}

// abcPitch converts a MIDI note number to an ABC pitch token. In ABC, the bare
// uppercase letters C..B are the octave starting at middle C (MIDI 60..71);
// lowercase letters are one octave higher, commas lower the octave and
// apostrophes raise it.
func abcPitch(midi int) string {
	pc := ((midi % 12) + 12) % 12
	octave := midi/12 - 1 // MIDI 60 -> octave 4
	cls := abcPitchClass[pc]

	var sb strings.Builder
	sb.WriteString(cls.accident)
	switch {
	case octave >= 5:
		sb.WriteByte(cls.letter + ('a' - 'A')) // lowercase
		for i := 0; i < octave-5; i++ {
			sb.WriteByte('\'')
		}
	default:
		sb.WriteByte(cls.letter) // uppercase = octave 4
		for i := 0; i < 4-octave; i++ {
			sb.WriteByte(',')
		}
	}
	return sb.String()
}

// sanitizeField keeps a string safe for a single-line ABC information field.
func sanitizeField(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return s
}
